// require "http://angular-ui.github.io/ui-router/release/angular-ui-router.min.js"
// require "app/main.coffee"
// require "app/controllers/actions_controller.coffee"
// require "app/controllers/application_controller.coffee"
// require "app/controllers/projects_controller.coffee"
// require "app/controllers/responses_controller.coffee"
// require "app/controllers/retros_controller.coffee"
// require "app/resources/action.coffee"
// require "app/resources/project.coffee"
// require "app/resources/project_retro.coffee"
// require "app/resources/retro.coffee"
// require "app/resources/retro_response.coffee"
// require "config/constants.coffee"
//=require "config/csrf.coffee"
// require "config/debug.coffee"
// require "config/push-state.coffee"
// require "config/routes.coffee"
// require "config/utf8.coffee"